const data = [
  {
    isConsumable: false,
    isCursed: false,
    isFocus: false,
    name: "Padded Armor",
    type: "armor",
    baseValue: 0,
    desc: "Soft and comfortable padded armor, offering basic protection.",
    flavor: "This armor is made of quilted layers of cloth and batting.",
    effects: [],
    properties: {
      armorClass: 0,
      requirement: undefined,
      hasStealthDisadvantage: false,
    },
    bonus: [],
  },
  {
    isConsumable: false,
    isCursed: false,
    isFocus: false,
    name: "Leather Armor",
    type: "armor",
    baseValue: 0,
    desc: "Armor made from tanned animal hide, offering moderate protection.",
    flavor: "This armor is supple and flexible, allowing for ease of movement.",
    effects: [],
    properties: {
      armorClass: 0,
      requirement: undefined,
      hasStealthDisadvantage: false,
    },
    bonus: [],
  },
  {
    isConsumable: false,
    isCursed: false,
    isFocus: false,
    name: "Fur Armor",
    type: "armor",
    baseValue: 0,
    desc: "Armor made from thick animal fur, offering warmth and some protection.",
    flavor: "This armor is warm and cozy, perfect for cold climates.",
    effects: [],
    properties: {
      armorClass: 0,
      requirement: undefined,
      hasStealthDisadvantage: false,
    },
    bonus: [],
  },
  {
    isConsumable: false,
    isCursed: false,
    isFocus: false,
    name: "Studded Armor",
    type: "armor",
    baseValue: 0,
    desc: "Leather armor reinforced with metal studs, offering good protection.",
    flavor:
      "This armor is a bit heavier than regular leather, but offers better protection.",
    effects: [],
    properties: {
      armorClass: 0,
      requirement: undefined,
      hasStealthDisadvantage: false,
    },
    bonus: [],
  },
  {
    isConsumable: false,
    isCursed: false,
    isFocus: false,
    name: "Chain Armor",
    type: "armor",
    baseValue: 0,
    desc: "Armor made from interlocking metal rings, offering excellent protection.",
    flavor: "This armor is heavy and noisy, but it provides excellent defense.",
    effects: [],
    properties: {
      armorClass: 0,
      requirement: undefined,
      hasStealthDisadvantage: true,
    },
    bonus: [],
  },
  {
    isConsumable: false,
    isCursed: false,
    isFocus: false,
    name: "Bronze Armor",
    type: "armor",
    baseValue: 0,
    desc: "Armor made from solid bronze plates, offering superior protection.",
    flavor:
      "This armor is heavy and sturdy, providing excellent defense at the cost of mobility.",
    effects: [],
    properties: {
      armorClass: 0,
      requirement: undefined,
      hasStealthDisadvantage: true,
    },
    bonus: [],
  },
  {
    isConsumable: false,
    isCursed: false,
    isFocus: false,
    name: "Iron Armor",
    type: "armor",
    baseValue: 0,
    desc: "Armor made from solid iron plates, offering the highest level of protection.",
    flavor:
      "This armor is extremely heavy and durable, providing unmatched defense.",
    effects: [],
    properties: {
      armorClass: 0,
      requirement: undefined,
      hasStealthDisadvantage: true,
    },
    bonus: [],
  },
];

export const getArmors = () => data;
